# Generated by Django 5.0.2 on 2025-01-31 18:17

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question (English)')),
                ('answer', django_quill.fields.QuillField(verbose_name='Answer (English)')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('answer_hi', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Answer (Hindi)')),
                ('question_bn', models.TextField(blank=True, null=True, verbose_name='Question (Bengali)')),
                ('answer_bn', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Answer (Bengali)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
