# Generated by Django 5.0.2 on 2025-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='auto_translate',
            field=models.BooleanField(default=True, help_text='Automatically translate content to other languages', verbose_name='Auto-translate'),
        ),
        migrations.AddField(
            model_name='faq',
            name='last_translated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last time translations were updated', null=True),
        ),
    ]
